---
require-stack-version: ">= 2.13.1"
concurrent-tests: false
system-ghc: true
install-ghc: false
resolver: nightly-2024-01-01
compiler: ghc-9.8.1

ghc-options:
  "$locals":
    -fwrite-ide-info
    -hiedir=.hie
    -fhide-source-paths
    -fignore-optim-changes
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-kind-signatures
    -Wno-missing-import-lists
    -Wno-missing-export-lists
    -Wno-incomplete-uni-patterns
    -Wno-partial-fields
    -Wno-implicit-prelude
    -Wno-deriving-typeable
    -Wno-missing-safe-haskell-mode

packages:
  - cards-discover
  - arkham-core
  - arkham-api
  - validate

allow-newer: true

extra-deps:
- github: halogenandtoast/monad-validate
  commit: e5f36d4a82875c09c6000fed8f8ced50e21b75ce
- github: MercuryTechnologies/esqueleto
  commit: 94d27de57072a823d97bd9868b33c45545c067c4
- websockets-0.12.7.3@sha256:3ecf458d4e1ffa64b61bce3c127ab5fff9be61fa2a246774e6e36c0ea1d4ad10,8237
- yesod-websockets-0.3.0.3@sha256:99f49618f7cbb944c928d2870872b6ff867602c80af5d83421a68feb2ad94186,1068
- wai-websockets-3.0.1.2@sha256:0e713ddb8c28d47be76cefeab3a73b6876477d648ddcd873ba6b15d08691aa7f,1905
