---
require-stack-version: ">= 2.3.1"
concurrent-tests: false

resolver: lts-18.0

# NB. -fignore-optim-changes can get in the way of profiling projects. To
# build for profiling, consider using a separate .stack-work directory or
# reversing the flag using `fno-ignore-optim-changes`.
#
# TODO: We should seek to remove -Wno-warn-deriving-strategies by adding
# explicit strategies throughout.
#
ghc-options:
  "$locals":
    -fhide-source-paths
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-import-lists
    -Wno-missing-export-lists
    -Wno-incomplete-uni-patterns
    -Wno-partial-fields
    -Wno-implicit-prelude
    -Wno-deriving-typeable
    -Wno-missing-monadfail-instances
    -fignore-optim-changes
    -fwrite-ide-info
    -hiedir=.hie
    -Wno-missing-safe-haskell-mode
    -Wno-prepositive-qualified-module

packages:
  - arkham-core
  - arkham-api
  - cards-discover

extra-deps:
- monoidal-containers-0.6.0.1@sha256:7d776942659eb4d70d8b8da5d734396374a6eda8b4622df9e61e26b24e9c8e40,2501
- unordered-containers-0.2.12.0
- aeson-1.5.4.1@sha256:6e4da18b16c1a9fb399f5544a357be7c82fe7c4300197de64928cb527b67957a,6906
- data-fix-0.3.0@sha256:058a266d1e658500e0ffb8babe68195b0ce06a081dcfc3814afc784b083fd9a5,1645
- strict-0.4@sha256:1b50c7c9c636c3a1bbc7f8873b9be48f6ca0faca4df6eec6a014de6208fb1c0e,4200
- classy-prelude-yesod-1.5.0@sha256:8f7e183bdfd6d2ea9674284c4f285294ab086aff60d9be4e5d7d2f3c1a2b05b7,1330
