name: arkham-core

language: GHC2021

dependencies:
- base

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- FunctionalDependencies
- GADTs
- LambdaCase
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RecordWildCards
- TypeFamilies
- TypeOperators
- UndecidableInstances
- ViewPatterns
- StrictData

library:
  source-dirs: library
  dependencies:
    - aeson
    - lens
    - unordered-containers
    - monoidal-containers
    - safe
    - these
    - classy-prelude
    - uuid
    - random-shuffle
    - containers
    - text
    - MonadRandom
    - extra
    - aeson-casing
    - aeson-diff
    - mtl
    - these-lens
    - semialign
    - pretty-simple
    - template-haskell
    - newtype
    - constraints
    - transformers

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts -O0 "-with-rtsopts=-N"
    dependencies:
      - arkham-core
      - hspec
      - hspec-expectations-lifted
      - lens
      - these
      - uuid
      - unordered-containers
      - mtl
      - random
      - containers
