name: arkham-core

dependencies:
- base >= 4.7 && < 5

default-extensions:
- AllowAmbiguousTypes
- BangPatterns
- BlockArguments
- ConstraintKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- ImportQualifiedPost

library:
  source-dirs: library
  dependencies:
    - aeson >= 1.5.4.1
    - lens
    - unordered-containers >= 0.2.12.0
    - hashable
    - safe
    - these
    - classy-prelude
    - uuid
    - random
    - random-shuffle
    - containers
    - text
    - vector
    - MonadRandom
    - extra
    - aeson-casing
    - mtl
    - these-lens
    - semialign
    - pretty-simple

executables:
  validate:
    main: main.hs
    source-dirs: validate
    ghc-options: -threaded -O2 "-with-rtsopts=-N -T -I0"
    other-modules: []
    dependencies:
      - classy-prelude
      - arkham-core
      - aeson
      - directory
      - text
      - MonadRandom

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts -O0 "-with-rtsopts=-N"
    dependencies:
      - classy-prelude
      - arkham-core
      - hspec
      - hspec-core
      - hspec-expectations
      - hspec-expectations-lifted
      - lens
      - these
      - uuid
      - unordered-containers >= 0.2.12.0
      - mtl
      - MonadRandom
      - random
