name: arkham-cli

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - NoImplicitPrelude
  - RecordWildCards
  - DerivingStrategies
  - DeriveGeneric
  - DeriveAnyClass
  - LambdaCase
  - FlexibleInstances
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - TypeApplications
  - TupleSections
  - FlexibleContexts
  - ConstraintKinds
  - StandaloneDeriving
  - DerivingVia

executables:
  arkham-cli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - unordered-containers >= 0.2.11.0
      - classy-prelude
      - pretty-simple
      - http-conduit
      - arkham-core
